[DEBUG|daemon.py:36] 2020-08-03 00:16:18,545 > initialized....
[WARNING|daemon.py:233] 2020-08-03 00:16:18,551 > (2003, "Can't connect to MySQL server on 'localhost' ([Errno 61] Connection refused)")
[DEBUG|daemon.py:36] 2020-08-03 00:16:18,552 > initialized....
[WARNING|daemon.py:233] 2020-08-03 00:16:18,554 > (2003, "Can't connect to MySQL server on 'localhost' ([Errno 61] Connection refused)")
[DEBUG|daemon.py:36] 2020-08-03 00:16:18,555 > initialized....
[WARNING|daemon.py:233] 2020-08-03 00:16:18,557 > (2003, "Can't connect to MySQL server on 'localhost' ([Errno 61] Connection refused)")
[DEBUG|daemon.py:36] 2020-08-03 00:16:18,558 > initialized....
[WARNING|daemon.py:233] 2020-08-03 00:16:18,561 > (2003, "Can't connect to MySQL server on 'localhost' ([Errno 61] Connection refused)")
